apiVersion: v1
kind: Service
metadata:
  name: nextclouddb
  labels:
    app: nextcloud
spec:
  ports:
    - port: 3306
  selector:
    app: nextcloud
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextclouddb
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
        tier: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: root-password
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_USER
          value: testuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: user-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: efs-mysql
