apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: passwordsecret
  literals:
  - root-password=root
  - user-password=testpass
  - nextcloud-password=nextadminpass
resources:
  - create-efs-provisioner.yaml
  - create-rbac.yaml
  - create-storage.yaml
  - deploy-mysql.yaml
  - deploy-nextcloud.yaml